#!/bin/bash
source /usr/local/lib/testadura/common/default-colors.sh
source /usr/local/lib/testadura/common/version.sh

# Default gateway (overall)
GW=$(ip route show default 2>/dev/null | awk '/^default/ {print $3; exit}')
DNS=$(resolvectl status 2>/dev/null \
      | awk -F': ' '/DNS Servers/ {print $2}' \
      | tr ' ' '\n' | sort -u | xargs)
[ -n "$DNS" ] || DNS=$(awk '/^nameserver/ {print $2}' /etc/resolv.conf | xargs)

UPTIME=$(uptime -p | sed 's/up //')
MEM_USED=$(free -h | awk '/^Mem:/ {print $3 "/" $2}')
DISK_USED=$(df -h / | awk 'NR==2 {print $3 "/" $2 " (" $5 ")"}')
LOADAVG=$(awk '{print $1", "$2", "$3}' /proc/loadavg)

STAMP="/var/lib/apt/periodic/update-success-stamp"
if [[ -f $STAMP ]]; then
    last_update=$(date -r "$STAMP" +%s)
    now=$(date +%s)
    days=$(( (now - last_update) / 86400 ))
    formatted_date=$(date +"%a, %d %b %Y %H:%M" -r "$STAMP")
    LAST_UPDATE="$formatted_date ($days day$([[ $days -ne 1 ]] && echo s) ago)"
else
    LAST_UPDATE="Never"
    ((days=9999))
fi

# Theme
ttl=$BRIGHT_YELLOW
lbl=$YELLOW
txt=$SILVER
dsc=$WHITE
rst=$RESET

printf "=========================================================================================\n"
printf " ${ttl}SolidgroundUX %s${rst}\n\n" "$SGND_VERSION"
printf " ${lbl}Build date :${rst} %s\n" "$SGND_VERSION_DATE"
printf "\n"
printf " © 2025 Mark Fieten — Testadura Consultancy\n"
printf " Licensed under the Testadura Non-Commercial License (TD-NC) v1.0.\n"
printf "-----------------------------------------------------------------------------------------\n\n"
printf "${lbl}SolidgroundUX${rst} provides a structured runtime for disciplined Bash tooling.\n\n"
printf "  • Deterministic bootstrap lifecycle\n"
printf "  • Declarative argument parsing\n"
printf "  • Unified state and configuration handling\n"
printf "  • Structured UI and logging primitives\n"
printf "  • Consistent deployment and packaging conventions\n\n"
printf "Designed for engineers who prefer clarity over magic,\n"
printf "and control over convenience.\n"
printf "=========================================================================================\n"
